### ISSUE TITLE
Can't run on wayland

### ISSUE THREAD

**Issue by elcste** [FBReader/FBReader-snap#1]
Trying to open the FBReader snap on wayland — using both the Ubuntu default GNOME wayland sessions and Sway — I get the following crash:

```
$ fbreader
+ unset XDG_CONFIG_HOME
+ unset XDG_DATA_HOME
+ exec /snap/fbreader/5/bin/FBReader
qt.qpa.plugin: Could not find the Qt platform plugin "wayland-egl" in ""
This application failed to start because no Qt platform plugin could be 
initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Aborted (core dumped)
```

**Comment by geometer** [comment]
Probably fixed. @elcste, could you please confirm? New snap is live.

**Comment by elcste** [comment]
@geometer Yes, I can confirm the latest snap opens in Ubuntu jammy (dev version for 22.04 LTS) in the default Ubuntu GNOME/Wayland session and in Sway.
